# This workflow is meant to be used to build compatible plugin  with composer without shopware store

name: Build Plugin 
on:
  workflow_dispatch:
  pull_request:
env:
  shopwareVersion: '6.5.7'

jobs:      
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Set version"
    outputs:
      shopwareVersion: ${{ env.shopwareVersion }}
      
  Build:
    needs: Setup
    container: ghcr.io/friendsofshopware/platform-plugin-dev:v${{ needs.Setup.outputs.shopwareVersion }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install shopware-cli
        uses: FriendsOfShopware/shopware-cli-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Plugin
        run: |
          shopware-cli --version
          shopware-cli extension build . 

      - name: Create zip and install devs
        run: |
          make zip
          ls -a ../.build
          echo "ZIP_FILENAME=$(ls -1t ../.build  | head -n 1)" >> $GITHUB_ENV
          composer --version
          # make dev

      - name: Validate plugin zip for shopware store compatibility
        run: |
          shopware-cli extension validate ../.build/$ZIP_FILENAME

      - name: Set plugin name and run stan test
        run: |
          echo "PLUGIN_NAME=$(echo $ZIP_FILENAME | grep -E '^[a-zA-Z]+' -o)" >> $GITHUB_ENV
          # make stan
          
      - name: Upload artifacts to git
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts
          path: ../.build/
          
      - name: Copy zip to staging SW 6.5
        uses: garygrossgarten/github-action-scp@release   
        with:
          local: ../.build
          remote: ${{ secrets.HOST_PATH }}
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.STAGING_SW65_USER }}
          password: ${{ secrets.STAGING_SW65_SECRET }}

     
      - name: Install plugin on staging SW 6.5
        env:
          REMOTE_PATH: ${{ secrets.HOST_PATH }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.STAGING_SW65_USER }}
          password: ${{ secrets.STAGING_SW65_SECRET }}
          envs: ZIP_FILENAME, PLUGIN_NAME, REMOTE_PATH
          script: |
            cd $REMOTE_PATH
            pwd
            bin/console plugin:zip-import $ZIP_FILENAME
            bin/console plugin:update $PLUGIN_NAME       
            bin/console plugin:install -a $PLUGIN_NAME
            bin/console cache:clear
            rm -rf $ZIP_FILENAME
            