# This workflow is meant to be used to build plugin  with composer and create github release without shopware store

name: Create Release
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
env:
  shopwareVersion: '6.5.7'

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Set version"
    outputs:
      shopwareVersion: ${{ env.shopwareVersion }}

  Release:
    if: github.event.pull_request.merged == true
    needs: Setup
    container: ghcr.io/friendsofshopware/platform-plugin-dev:v${{ needs.Setup.outputs.shopwareVersion }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Specify safe directory for git
        run: |
            git config --global --add safe.directory $(pwd)

      - name: Install shopware-cli
        uses: FriendsOfShopware/shopware-cli-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Plugin
        run: |
          shopware-cli --version
          shopware-cli extension build . 

      - name: Create zip and install devs
        run: |
          make zip
          ls -a ../.build
          echo "ZIP_FILENAME=$(ls -1t ../.build  | head -n 1)" >> $GITHUB_ENV
          # make dev

      - name: Validate plugin zip for shopware store compatibility
        run: |
          shopware-cli extension validate ../.build/$ZIP_FILENAME

      - name: Set plugin name and run stan test
        run: |
          echo "PLUGIN_NAME=$(echo $ZIP_FILENAME | grep -E '^[a-zA-Z]+' -o)" >> $GITHUB_ENV
          # make stan
          
      - name: Upload artifacts to git
        uses: actions/upload-artifact@v1
        with:
          name: build-artifacts
          path: ../.build/

      - name: Create zip with makefile
        run: |
          ls -a
          make zip
        
      - name: Get version
        run: >
            echo "EXTENSION_VERSION=$(jq ".version" composer.json -r)" >> $GITHUB_ENV
      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with:
          tag: v${{ env.EXTENSION_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
            
      - name: Extract changelog for release version
        shell: bash
        working-directory: ${{ github.workspace }}
        run: >
          echo "Pattern used for sed: /^## \\[${EXTENSION_VERSION}\\]/,/^## / ! d"       
          
          sed -e "/^## \\[${EXTENSION_VERSION}\\]/,/^## / ! d" CHANGELOG.md | head -n -1 >> RELEASE.md            
          
          printf "\n" >> RELEASE.md          
          
          cat RELEASE.md 
            
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ../.build/*.zip
          tag: v${{ env.EXTENSION_VERSION }}
          name: v${{ env.EXTENSION_VERSION }}
          commit: main
          bodyFile: ./RELEASE.md
